config/routes.rb
Dutyfree::Application.routes.draw do

  resources :line_items

  resources :carts

  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'abouts#index'

  resources :stocks

  resources :deliveries

  resources :users

  resources :static_pages

  resources :sales_rules

  resources :categories do
    resources :products
  end

  resources :contacts, only: [:new, :create]

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :line_items, :dependent => :destroy
  belongs_to :order

  def add_product(product_id)
    current_item = line_items.where(:product_id => product_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end


  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products, as: :categories, dependent: :destroy

  validates :name, :presence => true

  def self.cached_find(id)
    Rails.cache.fetch([name, id], expires_in: 5.minutes) { find(id) }
  end

  def self.cached_categories
    Rails.cache.fetch([name, id], expires_in: 5.minutes) { all.to_a }
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "My Contact Form",
        :to => "kgrini@mail.ru",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base

  validates :description, :presence => true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    product.price * quantity
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :carts
  has_many :line_items, :dependent => :destroy

  validates :name, :presence => true, :length => {:minimum => 4, :maximum => 20}
  validates :address, :presence => true, :length => {:minimum => 4, :maximum => 20}
  validates :phone, :presence => true, :length => {:minimum => 4, :maximum => 20}, :numericality => { :only_integer => true}

  VALIDATE_EMAIL = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, :presence => true, :format => { :with => VALIDATE_EMAIL}

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :categories, polymorphic: true


  #before_destroy :ensure_not_referenced_by_any_line_item

  validates :name, :presence => true

  validates :description, :presence => true

  validates :price, :presence => true, :numericality => { greater_than_or_equal_to: 0.01 }

  validates :size, :presence => true, :numericality => { greater_than_or_equal_to: 0.01 }


  mount_uploader :images, ImagesUploader, :allow_blank => true


  #def ensure_not_referenced_by_any_line_item
  #  if line_items.count.zero?
  #    return true
  #  else
  #    errors.add(:base, "Line items present")
  #    return false
  #  end
  #end


end

app/models/sales_rule.rb
class SalesRule < ActiveRecord::Base

  validates :description, :presence => true
end

app/models/stock.rb
class Stock < ActiveRecord::Base

  validates :description, :presence => true

  mount_uploader :images, ImagesUploader, :allow_blank => true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  before_save :create_remember_token

  before_save { |user| user.name = user.name.downcase}

  validates :name, :presence => true

  validates :email, :presence => true

  validates :password, :presence => true, :length => { :minimum => 6}

  validates :password_confirmation, :presence => true


private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def all_categories
    @menu_categories = Category.cached_categories
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def show_products
    @products= Product.order("created_at DESC").paginate(:page => params[:page].to_i + 1, :per_page => 12)
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/messages/_form.html.erb
<% form_for(message) do |f| %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :content, "Message" %><br />
      <%= f.text_area :content, :rows => 5 %>
    </div>
    <div class="actions"><%= f.submit "Send Message" %></div>
<% end %>

app/views/shared/_bg_images.html.erb
<section class = "phone"> </section>
<section class = "bottle"> </section>
<section class = "top_light"></section>

app/views/shared/_categories.html.erb
<section class="categories_title">
 </section>
<section>
    <ul class="categories_list">
      <% @menu_categories.each do |category| %>
            <a href="<%= category_path(category.id) %>">
              <li >
                <b><%= category.name %></b>
              </li>
            </a>
          <li>
            <section class = "hr_category">
            </section>
          </li>
      <% end %>
    </ul>
</section>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id = "error">
      <div class="alert alert-error">
        The form contains errors <%= pluralize(object.errors.count, "error") %>
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_header.html.erb
  <section class = "original_design"></section>
  <section class = "logo"> </section>
  <section class = "hours"> </section>
  <nav class = "navigation">
    <ul  class="button" >
      <section>
      <a href="<%= root_path %>">
        <li class="main_button">
        </li>
      </a>
      <a href="<%= categories_path %>" >
        <li  class="catalog_button">
        </li>
      </a>
      <a href="<%= cart_path(@cart) %>">
        <li  class="delivery_button">
        </li>
      </a>
      <a href="<%= sales_rules_path %>">
        <li  class="rules_button">
        </li>
      </a>
      <a href="<%= stocks_path %>">
        <li  class="stocks_button">
        </li>
      </a>
      <a href="<%= new_contact_path %>">
        <li  class="contact_button">
        </li>
      </a>
      </section>
    </ul>
  </nav>

app/views/shared/_product_preview.html.erb
<ul id="products_list">
    <% view_products.each do |product| %>
      <li class="product_form" >
          <section  class = "product_name_background">

          </section>

        <a href="<%= category_product_path(product.categories_id, product.id) %>" class = "product_link">
          <%= product.name %>
        </a>
          <%= image_tag product.images_url(:thumb), :class => "img" %>
       </li>
    <% end %>
  <%= will_paginate view_products %>
</ul>

app/views/shared/_products_block.html.erb
<!--<section class="products_background">-->
<!--</section>-->
<section class = "last_added_products_title">
</section>
<section>
     <%= render "shared/product_preview", :view_products => @products %>
</section>