config/routes.rb
Dutyfree::Application.routes.draw do

  resources :line_items

  resources :carts

  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'abouts#index'

  resources :stocks

  resources :deliveries

  resources :users

  resources :static_pages

  resources :sales_rules

  resources :categories do
    resources :products
  end

  resources :contacts, only: [:new, :create]

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :line_items, :dependent => :destroy
  belongs_to :order

  def add_product(product_id)
    current_item = line_items.where(:product_id => product_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end


  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products, as: :categories, dependent: :destroy

  validates :name, :presence => true

  def self.cached_find(id)
    Rails.cache.fetch([name, id], expires_in: 5.minutes) { find(id) }
  end

  def self.cached_categories
    Rails.cache.fetch([name, id], expires_in: 5.minutes) { all.to_a }
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "My Contact Form",
        :to => "kgrini@mail.ru",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base

  validates :description, :presence => true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    product.price * quantity
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :carts
  has_many :line_items, :dependent => :destroy

  validates :name, :presence => true, :length => {:minimum => 4, :maximum => 20}
  validates :address, :presence => true, :length => {:minimum => 4, :maximum => 20}
  validates :phone, :presence => true, :length => {:minimum => 4, :maximum => 20}, :numericality => { :only_integer => true}

  VALIDATE_EMAIL = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, :presence => true, :format => { :with => VALIDATE_EMAIL}

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :categories, polymorphic: true


  #before_destroy :ensure_not_referenced_by_any_line_item

  validates :name, :presence => true

  validates :description, :presence => true

  validates :price, :presence => true, :numericality => { greater_than_or_equal_to: 0.01 }

  validates :size, :presence => true, :numericality => { greater_than_or_equal_to: 0.01 }


  mount_uploader :images, ImagesUploader, :allow_blank => true


  #def ensure_not_referenced_by_any_line_item
  #  if line_items.count.zero?
  #    return true
  #  else
  #    errors.add(:base, "Line items present")
  #    return false
  #  end
  #end


end

app/models/sales_rule.rb
class SalesRule < ActiveRecord::Base

  validates :description, :presence => true
end

app/models/stock.rb
class Stock < ActiveRecord::Base

  validates :description, :presence => true

  mount_uploader :images, ImagesUploader, :allow_blank => true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  before_save :create_remember_token

  before_save { |user| user.name = user.name.downcase}

  validates :name, :presence => true

  validates :email, :presence => true

  validates :password, :presence => true, :length => { :minimum => 6}

  validates :password_confirmation, :presence => true


private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :authenticate_admin_user!, :only => [:new, :create, :edit, :update, :destroy, :index]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :load_categories
  before_action :all_categories, :only => [:new, :index, :edit, :show, :create]
  before_action :show_products, :only => [:index, :show]

  def index
    @categories = Category.find(params[:category_id])
    @products = @categories.products.paginate(:page => params[:page], :per_page => 2)
  end

  def new
    @product = @categories.products.new
  end

  def create
    @product = @categories.products.new(product_params)
    if @product.save
      flash[:success] = "Hoorey"

      respond_to do |format|
        format.html {}
        format.js
      end
    else
      flash[:error] = "Fill all fields"
      render :new
    end
  end

  def show
    @cart = current_cart
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
     redirect_to [@categories, @product]
    else
     render 'edit'
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Product was deleted"
    redirect_to @categories
  end

  def set_product
    begin
      @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Попытка доступа к несуществующему продукту #{params[:id]}"
      redirect_to categories_path, :notice => "Продукта не существует"
    else

    end
  end

  def product_params
    params.require(:product).permit(:name, :description, :size, :price, :images, :categories_id, :categories_type)
  end

private
  def load_categories
    begin
      resource, id = request.path.split('/')[1, 2]
    rescue ActiveRecord::RecordNotFound
      @categories = resource.singularize.classify.constantize.find(id)
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def all_categories
    @menu_categories = Category.cached_categories
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def show_products
    @products= Product.order("created_at DESC").paginate(:page => params[:page].to_i + 1, :per_page => 12)
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/products/_all_products.html.erb
<ul>
  <% @products.each do |product| %>
    <li>
        <%=  link_to product.name, [@categories, product] %>
    </li>
  <% end %>
</ul>

app/views/products/_form.html.erb
<h4>Добавить продукт</h4>
<div class="form-group">
    <%= form_for [@categories, @product], :remote => true , :html => {:multipart => true} do |f| %>

        <%= render 'shared/error_messages', object: @product %>

        <%= f.text_field :name, :class => 'form-control', :placeholder => "Name"   %>

        <%= f.text_area :description, :class => 'form-control', :placeholder => "Description"    %>

        <%= f.number_field :size, :class => 'form-control', :placeholder => "Size"    %>

        <%= f.number_field :price, :class => 'form-control', :placeholder => "Price"    %>

        <%= f.file_field :images, :class => 'form-control' %>

        <%= f.submit 'Submit', :class => "btn btn-primary"%>

    <% end %>
</div>

app/views/products/edit.html.erb
<h4>Редактировать продукт</h4>
<div class="form-group">
  <%= form_for [@categories, @product], :html => {:multipart => true} do |f| %>

      <%= render 'shared/error_messages', object: @product %>
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'form-control'  %>

      <%= f.label :description %>
      <%= f.text_field :description, :class => 'form-control' %>

      <%= f.label :size %>
      <%= f.number_field :size, :class => 'form-control' %>

      <%= f.label :price %>
      <%= f.number_field :price, :class => 'form-control' %>

      <%= f.label :images %>
      <%= f.file_field :images, :class => 'form-control' %>

      <%= f.submit 'Submit', :class => "btn btn-primary" %>

  <% end %>
</div>

app/views/products/index.html.erb
<h4>All products</h4>
<div>
    <%= render 'all_products' %>
</div>

app/views/products/new.html.erb
<section class="main_block">
    <%= render 'form' %>
</section>

app/views/products/show.html.erb
<% provide(:title, 'Товар') %>
<div class = "bkg_images">
  <%= render "shared/bg_images" %>
</div>
<header class = "header">
  <%= render "shared/header" %>
</header>
<section class = "categories">
  <%= render "shared/categories" %>
</section>
<section class="products_block">
  <section class="products_background">
  </section>
    <ul id="products_list">
        <li  class="product_form" >
            <%= image_tag @product.images_url(:thumb), :class => "img   " %>
        </li>
        <section class="product_description">
            <li>
                <b><%= t "products.show.name" %>:</b> <%= @product.name %>
            </li>
            <li>
              <b><%= t ".description" %>:</b> <%= @product.description %>
            </li>
            <li>
              <b><%= t ".weight" %>:</b> <%= @product.size %> gramms
            </li>
            <li>
              <b><%= t ".price" %>:</b> <%= @product.price %> mdl
            </li>
            <li>
                <%= button_to "Добавить в корзину", line_items_path(:product_id => @product), :remote => true, :id => "button" %>
            </li>
        </section>
    </ul>

</section>